name: junk

on:
  release:
    types: [created]



jobs:
  foo:    
    runs-on: ubuntu-latest

    steps:
      - name: echo env
        run: env
      - name: GITHUB_REF_NAME
        run: echo "$GITHUB_REF_NAME"
      - name: GITHUB_REF
        run: echo "$GITHUB_REF"
