name: junk

on:
  workflow_dispatch:
    
jobs:
  foo:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: curl -sS -f -I -H "Authorization: token ${{ secrets.GITHUB_TOKEN}}" https://api.github.com
      
#      - name: check permissions
#        run: ./check-permissions.sh ${{ secrets.GITHUB_TOKEN }}

