name: junk

on:
  workflow_dispatch:
    
jobs:
  foo:    
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - name: check permissions
        run: ./check-permissions.sh ${{ secrets.GITHUB_TOKEN }}

